os: linux
language: python
python: "3.7"
dist: bionic
install:
  - pip install conan
  - conan user
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - pip install -r covid_graphs/dev_requirements.txt
  - pip install covid_graphs/
jobs:
  include:
    - stage:
      - name: "C++ tests"
        script:
        - conan create -b gtest -b missing .
      - name: "Python tests"
        script:
        - pushd covid_graphs/
        - ./run_tests.sh
        - popd
script: echo "hello"