os: linux
language: python
python: "3.7"
dist: bionic
matrix:
  include:
    - name: "Conan C++ tests"
      install:
        - pip install conan
        - conan profile new default --detect
        - conan profile update settings.compiler.libcxx=libstdc++11 default
      script:
        - conan create .
    - name: "Python tests"
      install:
        - pip install -r covid_graphs/dev_requirements.txt
        - pip install covid_graphs/
      script:
        - pushd covid_graphs/
        - ./run_tests.sh
        - popd
    - name: "Graphs web app"
      language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      script:
        - cd covid_graphs/react-web/
        - npm install
        - npm test
        - npm run build
