os: linux
language: python
python: "3.7"
dist: bionic
install:
  - pip install conan
  - conan user
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
script:
  - conan create -b gtest -b missing .
