os: linux
language: python
python: "3.7"
dist: bionic
matrix:
  include:
    - name: "Conan C++ tests"
      install:
        - pip install conan
        - conan profile new default --detect
        - conan profile update settings.compiler.libcxx=libstdc++11 default
      script:
        - conan create .
    - name: "Python tests"
      install:
        - pip install -r python/dev_requirements.txt
        - pip install python/covid_graphs/
        - pip install python/covid_web/
      script:
        - pushd python/
        - ./run_tests.sh
        - popd
    - name: "Graphs web app"
      language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      script:
        - cd web/react-web/
        - npm install
        - npm test
        - npm run build
