version: "2.2"

services:
  dash_server:
    build: covid_graphs/
    image: covid19_predictions
    volumes:
      - "./data:/covid19/data:ro"
    working_dir: "/covid19"
    ports:
      - 127.0.0.1:8081:8081
    restart: always
    command: "covid_graphs.run_server --data-dir data"
