version: "2.2"

services:
  dash_server:
    build: graphs/
    image: accu_dash
    volumes:
      - "./graphs:/covid19/graphs:ro"
      - "./data:/covid19/data:ro"
    working_dir: "/covid19"
    ports:
      - 127.0.0.1:8081:8080
    restart: always
    command: "python3 /covid19/graphs/growth.py /covid19/data ALL"
