version: "2.2"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - "react-web:/app/covid19/graphs/"
      - "./web/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 127.0.0.1:8081:80
    restart: always
  flask_server:
    build: .
    image: flask_server
    volumes:
      - "./data:/covid19/data:ro"
    environment:
      DATA_PATH: "/covid19/data/"
    restart: always
    command: "uwsgi --uid www-data --gid www-data --socket 0.0.0.0:5000 --die-on-term -w covid_web.wsgi:app"
  react-web-deploy:
    build: web/react-web/
    image: react-web-builder
    volumes:
      - "react-web:/react-web"
    command: "bash -c ' rm -rf /react-web/* && cp -a . /react-web/'"

volumes:
  react-web:
