version: "2.2"

services:
  dash_server:
    build: covid_graphs/
    image: accu_dash
    volumes:
      - "./data:/covid19/data:ro"
    working_dir: "/covid19"
    ports:
      - 127.0.0.1:8081:8081
    restart: always
    command: "covid_graphs.run_server --data-dir data/ --simulated-polynomial data/results-poly.pb --simulated-exponential data/results-exp.pb"
