# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: country_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='country_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12\x63ountry_data.proto\"\xa1\x01\n\nDailyStats\x12\x0c\n\x04\x64\x65\x61\x64\x18\x01 \x01(\x05\x12\x10\n\x08positive\x18\x02 \x01(\x05\x12\x11\n\trecovered\x18\x03 \x01(\x05\x12\x0e\n\x06tested\x18\x04 \x01(\r\x12\x1e\n\x04\x64\x61te\x18\x05 \x01(\x0b\x32\x10.DailyStats.Date\x1a\x30\n\x04\x44\x61te\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\r\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0c\n\x04year\x18\x03 \x01(\r\"_\n\x0b\x43ountryData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nshort_name\x18\x03 \x01(\t\x12\x12\n\npopulation\x18\x04 \x01(\x04\x12\x1a\n\x05stats\x18\x02 \x03(\x0b\x32\x0b.DailyStatsb\x06proto3'
)




_DAILYSTATS_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='DailyStats.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='DailyStats.Date.day', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='DailyStats.Date.month', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year', full_name='DailyStats.Date.year', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=184,
)

_DAILYSTATS = _descriptor.Descriptor(
  name='DailyStats',
  full_name='DailyStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dead', full_name='DailyStats.dead', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='positive', full_name='DailyStats.positive', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recovered', full_name='DailyStats.recovered', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tested', full_name='DailyStats.tested', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='DailyStats.date', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DAILYSTATS_DATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=184,
)


_COUNTRYDATA = _descriptor.Descriptor(
  name='CountryData',
  full_name='CountryData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CountryData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='short_name', full_name='CountryData.short_name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='population', full_name='CountryData.population', index=2,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats', full_name='CountryData.stats', index=3,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=281,
)

_DAILYSTATS_DATE.containing_type = _DAILYSTATS
_DAILYSTATS.fields_by_name['date'].message_type = _DAILYSTATS_DATE
_COUNTRYDATA.fields_by_name['stats'].message_type = _DAILYSTATS
DESCRIPTOR.message_types_by_name['DailyStats'] = _DAILYSTATS
DESCRIPTOR.message_types_by_name['CountryData'] = _COUNTRYDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DailyStats = _reflection.GeneratedProtocolMessageType('DailyStats', (_message.Message,), {

  'Date' : _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
    'DESCRIPTOR' : _DAILYSTATS_DATE,
    '__module__' : 'country_data_pb2'
    # @@protoc_insertion_point(class_scope:DailyStats.Date)
    })
  ,
  'DESCRIPTOR' : _DAILYSTATS,
  '__module__' : 'country_data_pb2'
  # @@protoc_insertion_point(class_scope:DailyStats)
  })
_sym_db.RegisterMessage(DailyStats)
_sym_db.RegisterMessage(DailyStats.Date)

CountryData = _reflection.GeneratedProtocolMessageType('CountryData', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYDATA,
  '__module__' : 'country_data_pb2'
  # @@protoc_insertion_point(class_scope:CountryData)
  })
_sym_db.RegisterMessage(CountryData)


# @@protoc_insertion_point(module_scope)
